version: '3.6'

services:
  fc-graphql-example:
    build: .
    volumes:
      - /root/log:/root/log
      - /tmp:/tmp
    environment:
      - SPRING.PROFILES.ACTIVE=dev
    ports:
      - 8080:8080
